[phases.setup]
nixPkgs = ["nodejs_20","chromium","nss","nspr","cups","libxkbcommon","xorg.libXcomposite","xorg.libXdamage","xorg.libXext","xorg.libXrandr","xorg.libxcb","mesa","expat","libdrm","xorg.libX11","xorg.libXfixes","glib","dbus","atk","gtk3","pango","cairo","gdk-pixbuf","udev","at-spi2-atk"]

[phases.install]
cmds = ["npm install", "npx playwright install chromium"]

[start]
cmd = "node index.js"
